import { useState } from "react";
import { ArrowRight, Check, Cloud, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { configureFirebase, getFirebaseAuth, parseFirebaseConfig } from "@/lib/cloud";
import { GoogleAuthProvider, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup } from "firebase/auth";

export default function Login() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [remember, setRemember] = useState(true); const [loading, setLoading] = useState(false);
  const getAuthReady = () => { const raw = localStorage.getItem("bayti-firebase-settings"); const config = raw ? parseFirebaseConfig(raw) : null; if (!config) { toast.error("افتح إعدادات بيتي وأدخل Firebase Config أولاً"); return null; } try { configureFirebase(config); return getFirebaseAuth(); } catch { toast.error("تعذر تهيئة Firebase"); return null; } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!email || !password) return toast.error("اكتب البريد الإلكتروني وكلمة المرور أولاً"); const auth = getAuthReady(); if (!auth) return; setLoading(true); try { await signInWithEmailAndPassword(auth, email, password); toast.success("تم تسجيل الدخول"); window.location.href = "/"; } catch { toast.error("البريد أو كلمة المرور غير صحيحين، أو لم يتم تفعيل Email Auth في Firebase"); } finally { setLoading(false); } };
  const googleLogin = async () => { const auth = getAuthReady(); if (!auth) return; setLoading(true); try { await signInWithPopup(auth, new GoogleAuthProvider()); toast.success("تم تسجيل الدخول بحساب Google"); window.location.href = "/"; } catch { toast.error("تعذر تسجيل الدخول بحساب Google"); } finally { setLoading(false); } };
  const createAccount = async () => { if (!email || !password) return toast.error("اكتب البريد وكلمة المرور لإنشاء الحساب"); const auth = getAuthReady(); if (!auth) return; setLoading(true); try { await createUserWithEmailAndPassword(auth, email, password); toast.success("تم إنشاء الحساب"); window.location.href = "/"; } catch { toast.error("تعذر إنشاء الحساب؛ تأكد من تفعيل Email/Password في Firebase"); } finally { setLoading(false); } };
  return <main className="login-page" dir="rtl"><div className="login-decoration decoration-one" /><div className="login-decoration decoration-two" /><section className="login-intro"><div className="login-brand"><div className="logo-mark"><WalletCards size={21} /></div><div><strong>بيتي</strong><span>ميزانية البيت</span></div></div><div className="login-message"><span className="eyebrow">بياناتك معاك في كل مكان</span><h1>نظّم فلوس بيتك،<br /><em>واطمن عليها.</em></h1><p>سجّل دخولك عشان نزامن مصاريفك وأهدافك بين الموبايل والويب بأمان.</p><div className="trust-points"><span><Check size={14} /> تعمل أوفلاين حتى بدون نت</span><span><ShieldCheck size={14} /> حماية Firebase</span><span><Cloud size={14} /> مزامنة تلقائية عند الاتصال</span></div></div><div className="login-intro-footer">١٠٠٪ تحكم في بياناتك · تقدر تصدّر نسخة في أي وقت</div></section><section className="login-card-wrap"><div className="login-card"><button className="back-link" onClick={() => window.location.href = "/"}><ArrowRight size={16} /> الرجوع للتطبيق</button><div className="login-card-heading"><div className="login-small-icon"><LockKeyhole size={19} /></div><span className="eyebrow">مساحتك الآمنة</span><h2>أهلاً بعودتك</h2><p>استخدم إعدادات Firebase التي حفظتها من التطبيق.</p></div><button className="google-button" onClick={googleLogin} disabled={loading}><span className="google-g">G</span> الدخول باستخدام حساب Google</button><div className="or-divider"><span>أو باستخدام البريد الإلكتروني</span></div><form onSubmit={submit}><label className="login-field"><span>البريد الإلكتروني</span><div><Mail size={17} /><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="name@example.com" autoComplete="email" /></div></label><label className="login-field"><span>كلمة المرور</span><div><LockKeyhole size={17} /><input type={showPassword ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••" autoComplete="current-password" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label="إظهار كلمة المرور">{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label><div className="login-options"><label><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} /><span className="checkmark"><Check size={12} /></span> تذكرني</label><button type="button" onClick={() => toast("فعّل Password Reset في Firebase لإرسال رابط الاستعادة")}>نسيت كلمة المرور؟</button></div><button className="login-submit" type="submit" disabled={loading}>{loading ? "جاري التحقق..." : "تسجيل الدخول"}</button></form><p className="signup-note">لسه معندكش حساب؟ <button onClick={createAccount} disabled={loading}>إنشاء حساب جديد</button></p></div><p className="login-legal">بتسجيل الدخول أنت توافق على شروط الاستخدام وسياسة الخصوصية.</p></section></main>;
}
